### ISSUE TITLE
Data Access Layer: Items Declaration

### ISSUE THREAD

**Issue by LorincziMatyas** [Edebala/CollegeNColleagues#3]
Item Declaration:

New files created: items.h items.cpp (C++ class)
New classes implemented: Item, Weapon, Armor, Throwable, Potion, HealingPotion, BuffPotion, WeaponBuffPotion, ArmorBuffPotion, StrengthenPotion

**Comment by Edebala** [comment]
-Items
-Armors
-Weapons
